[package]
name = "rust-learning"
version = "0.1.0"
authors = ["T-Sumida <ui.suto05@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
